import { StyleSheet } from 'react-native';

export const getStyles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      paddingHorizontal: 10,
      backgroundColor: theme.backgroundColor,
    },
    headerContainer: {
      padding: 10,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      elevation: 4,
      shadowColor: theme.shadowColor,//theme.shadowColor,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      width: '105%',
      left: -10,
    },
    headerImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      marginBottom: 10,
    },
    headerText: {
      fontSize: 18,
      fontWeight: 'bold',
      color: theme.textColor,
      textAlign: 'center',
    },
    headerTextContainer: {
      marginTop: 10,
      alignItems: 'center',
    },
    buttonHeader: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      width: '60%',
      marginTop: 10,
    },
    calendarContainer: {
      flex: 1,
      top: -10,
    },
    titleText: {
      fontSize: 20,
      fontWeight: 'bold',
      marginVertical: 12,
      color: theme.textColor,
      top: 0,
    },
    horariosRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 12,
      top: 0,
    },
    button_horario: {
      flex: 1,
      alignItems: 'center',
    },
    horarioContainer: {
      width: 90,
      height: 40,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 5,
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
    horatioimage: {
      width: 22,
      height: 22,
      marginBottom: 4,
    },
    button_horario_text: {
      fontSize: 14,
      fontWeight: 'bold',
    },
    btnAction: {
        position: 'absolute',
      bottom: 0,
      right: 10,
      marginTop: 16,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
      width: '30%',
    },
    btnActionag: {
        position: 'absolute',
      bottom: 0,
      marginTop: 16,
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
      width: '60%',
    },
    btnEnabled: {
      backgroundColor: '#4CAF50',
    },
    btnEnabledObs: {
      backgroundColor: '#2196F3',
    },
    btnDisabled: {
      backgroundColor: '#ccc',
    },
    btnText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
    textAlign: 'center',
    },
    centeredModal: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      width: '90%',
      backgroundColor: theme.cardBackground,
      padding: 16,
      borderRadius: 12,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOpacity: 0.25,
      shadowOffset: { width: 0, height: 2 },
      shadowRadius: 4,
      elevation: 5,
    },
    input: {
      width: '100%',
      height: 100,
      backgroundColor: '#f5f5f5',
      color: '#333',
      padding: 10,
      borderRadius: 8,
      marginBottom: 12,
      textAlignVertical: 'top',
    },
  });
