import { StyleSheet } from 'react-native';

export const getStyles = (theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundColor,
    },
    headerContainer: {
      padding: 10,
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      elevation: 4,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      width: '100%',
      left: 0,
    },
    headerImage: {
      width: 80,
      height: 80,
      resizeMode: 'contain',
      marginBottom: 10,
    },
    headerText: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.textColor,
      fontStyle: 'italic',
      textAlign: 'center',
    },
    headerTextContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginVertical: 5,
    },
    buttonHeader: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      width: '60%',
      marginTop: 10,
    },
    buttonContainer: {
      padding: 10,
      borderRadius: 50,
      backgroundColor: theme.secondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    contato: {
      marginHorizontal: 10,
    },
    calendarContainer: {
      flex: 1,
      paddingHorizontal: 10,
    },
    horariosTitle: {
      fontWeight: 'bold',
      fontSize: 18,
      marginTop: -10,
      marginBottom: 10,
      color: theme.textColor,
      textAlign: 'center',
    },
    horariosRow: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 7,
    },
    horarioContainer: {
      flex: 1,
      alignItems: 'center',
      marginHorizontal: 5,
    },
    horarioBox: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 60,
      height: 60,
      borderRadius: 50,
      borderColor: '#6542a1',
      padding: 0,
    },
    horarioImage: {
      width: 30,
      height: 30,
      resizeMode: 'contain',
    },
    horarioText: {
      fontWeight: 'bold',
      fontSize: 14,
      position: 'relative',
      top: -5,
    },
    buttonAgendar: {
      marginTop: 10,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      marginHorizontal: 30,
      elevation: 3,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      width: '60%',
      marginLeft: 10,
    },
    buttonAgendarText: {
      fontWeight: 'bold',
      fontSize: 16,
    },
    buttonObservacao: {
      marginTop: 10,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      marginHorizontal: 30,
      elevation: 3,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      width: '30%',
      marginRight: 20,
      marginLeft: -15,

    },
    buttonObservacaoText: {
      fontWeight: 'bold',
      fontSize: 16,
    },
    modal: {
      justifyContent: 'flex-end',
      margin: 0,
    },
    modalContainer: {
      backgroundColor: 'transparent',
      padding: 20,
      borderRadius: 10,
      width: '85%',
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 10,
      marginHorizontal: 20,
    },
    modalContent: {
      flexDirection: 'row',
      alignItems: 'center',
      borderColor: '#ddd',
      borderWidth: 1,
      borderRadius: 10,
      paddingHorizontal: 10,
      backgroundColor: 'white',
        borderWidth: 1,
      borderColor: '#ddd',
      borderRadius: 10,
      marginHorizontal: 20,
    },
    input: {
      flex: 1,
      height: 100,
      textAlignVertical: 'top',
      fontSize: 16,
      color: theme.textColor,
      padding: 10,
    },
    iconButton: {
      padding: 10,
    },
    footer: {
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.primary,
    },
    btnText: {
      color: theme.isNightMode ? 'black' : 'white',
      fontSize: 16,
      fontWeight: 'bold',
      textAlign: 'center',
      padding: 10,
    },
  });
